### ISSUE TITLE
Not blacklisting everything

### ISSUE THREAD

**Issue by bruvv** [NNScripts/nn-custom-scripts#2]
```
Homeland.S01E04.Allein.im.Regen.GERMAN.DUBBED.DL.720p.BLURAY.x264-euHD
```

With this blacklist:

```
[-.](danish|deutsch|dksubs|flemish|french|hebrew|german|ita-eng|japenese|japanese|korsub|norwegian|serbian|spanish|spanisch|swedish|swesub|turkish)[-.]
```

is not getting deleted. I understood that NN automaticly icnorsuppcases (/i) maybe change this in the script?

**Comment by NNScripts** [comment]
I changed the script so that PHP handles the regexes (case insensitive).
Before the script did a small conversion to make the regex mysql compatible, but it appears that wasn't enough.

**Comment by bruvv** [comment]
Zal wel overgaan op nederlands ;)

Dit was nadat ik het script had geupdate namelijk. Vandaar de issue ook.

**Comment by NNScripts** [comment]
klopt, en daarom heb ik het script aangepast.

MySQL gebruikt een ander soort regex library dan PHP.
Om de werking van een regex het zelfde te houden moest ik het dus in php oplossen.
Nu is het script iets trager, maar werkt het wel.

**Comment by bruvv** [comment]
Net weer getest alles schoon (map verwijderd en opnieuw tegevoegd)
simple search op german op de site krijg ik 12 pagina's vol.
Dit is er een:

```
Homeland.S01E04.Allein.im.Regen.GERMAN.DUBBED.DL.720p.BLURAY.x264-euHD
```

Zowel dubbed in the naam als german...

**Comment by NNScripts** [comment]
Welke regex gebruik je voor het zoeken naar "german"?
Want ik heb die naam gechecked tegen mijn blacklist, en daar wordt hij gevonden.

Mijn regex:
german|danish|flemish|french|swedish|swesub|deutsch|norwegian|\.ita\.|Ger\.Eng|SPANiSH|korsub|Giro|japanese|Turkish|DKsubs|\.Ita-Eng\.

[update]
Zeker dat je het script geupdate hebt? Want ook met de regex uit je repo (id: 100000) vind ik hem gewoon. (als ik een klein php test scriptje maak)
Welke versie van het script hebt je? want de laatste is momenteel 0.4

**Comment by bruvv** [comment]
```
[-.](danish|deutsch|dksubs|flemish|french|hebrew|german|ita-eng|japenese|japanese|korsub|norwegian|serbian|spanish|spanisch|swedish|swesub|turkish)[-.]
Blocks non-english language releases.
```

Die op mijn git te vinden is ;)

Verder draai ik 0.4 ook 
edit:
Probleem gevonden, dit zijn de "left overs" van een nzb import. Deze groups heb ik niet aanstaan en dus checkt hij ze ook niet! 

Zou je misschien het zo kunnen instellen dat je een optie hebt om de hele database te doen ?

**Comment by NNScripts** [comment]
idd een goede optie, ik zal er naar kijken.
Ik ben ook nog met een test tool bezig waarbij je een string op kunt geven, welke getest wordt tegen alle black/white lists (op alleen op de regexes voor een opgegeven groep). Je kan dan makkelijker kijken of een release titel matched.
